import { LoanRequest, Bid, Lender, AdminStats } from '@/types';

export const mockLoanRequests: LoanRequest[] = [
  {
    id: 'lr-001',
    student_id: 's-001',
    student_name: 'Keshav Singla',
    degree: 'B.Tech Computer Science',
    institution: 'Manipal Institute of Technology',
    institution_tier: 'NIT/Top-Private',
    course_duration_years: 4,
    loan_amount: 1800000,
    tenure_months: 84,
    purpose: 'Tuition fees, hostel accommodation, and laptop/equipment costs for a 4-year B.Tech program with a confirmed placement record of 94% above ₹8 LPA.',
    trust_score: {
      score: 81,
      tier: 'Low Risk',
      components: {
        institutionTier: 78,
        courseEmployability: 88,
        coApplicantStrength: 72,
        documentVerification: 95,
        incomeStability: 68,
      },
    },
    current_lowest_rate: 9.25,
    bid_count: 4,
    auction_ends_at: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'open',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    co_applicant: { name: 'Rajesh Singla', relation: 'Father', annual_income: 1200000 },
  },
  {
    id: 'lr-002',
    student_id: 's-002',
    student_name: 'Purva Jain',
    degree: 'MBBS (Medical)',
    institution: 'AIIMS New Delhi',
    institution_tier: 'IIT/IIM/AIIMS',
    course_duration_years: 5,
    loan_amount: 2500000,
    tenure_months: 120,
    purpose: 'Complete MBBS program at AIIMS New Delhi, covering tuition, clinical rotations, and research materials. AIIMS graduates have 100% placement with average starting salaries of ₹18 LPA in public sector.',
    trust_score: {
      score: 96,
      tier: 'Ultra-Low Risk',
      components: {
        institutionTier: 100,
        courseEmployability: 97,
        coApplicantStrength: 89,
        documentVerification: 100,
        incomeStability: 91,
      },
    },
    current_lowest_rate: 7.10,
    bid_count: 9,
    auction_ends_at: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'open',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    co_applicant: { name: 'Sunita Jain', relation: 'Mother', annual_income: 2200000 },
  },
  {
    id: 'lr-003',
    student_id: 's-003',
    student_name: 'Harshit Ohlyan',
    degree: 'MBA (Finance)',
    institution: 'IIM Ahmedabad',
    institution_tier: 'IIT/IIM/AIIMS',
    course_duration_years: 2,
    loan_amount: 3200000,
    tenure_months: 60,
    purpose: 'Two-year MBA program at IIM Ahmedabad. Average placement salary of ₹32 LPA (2024 batch). Strong summer internship track record. Full-time offer expected from investment banking sector.',
    trust_score: {
      score: 94,
      tier: 'Ultra-Low Risk',
      components: {
        institutionTier: 100,
        courseEmployability: 96,
        coApplicantStrength: 85,
        documentVerification: 100,
        incomeStability: 88,
      },
    },
    current_lowest_rate: 7.75,
    bid_count: 12,
    auction_ends_at: new Date(Date.now() + 18 * 60 * 60 * 1000).toISOString(),
    status: 'open',
    created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    co_applicant: { name: 'Vikram Ohlyan', relation: 'Father', annual_income: 1800000 },
  },
  {
    id: 'lr-004',
    student_id: 's-004',
    student_name: 'Ananya Krishnamurthy',
    degree: 'M.S. Data Science',
    institution: 'IIT Bombay',
    institution_tier: 'IIT/IIM/AIIMS',
    course_duration_years: 2,
    loan_amount: 950000,
    tenure_months: 60,
    purpose: 'Two-year M.S. in Data Science and AI at IIT Bombay. Research focus on NLP. Multiple conference papers submitted. Pre-placement offer expected from Google/Microsoft research division.',
    trust_score: {
      score: 92,
      tier: 'Ultra-Low Risk',
      components: {
        institutionTier: 100,
        courseEmployability: 95,
        coApplicantStrength: 78,
        documentVerification: 100,
        incomeStability: 82,
      },
    },
    current_lowest_rate: 7.40,
    bid_count: 7,
    auction_ends_at: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'open',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    co_applicant: { name: 'Lakshmi Krishnamurthy', relation: 'Mother', annual_income: 1600000 },
  },
  {
    id: 'lr-005',
    student_id: 's-005',
    student_name: 'Rohan Mehta',
    degree: 'B.Tech Mechanical',
    institution: 'NIT Trichy',
    institution_tier: 'NIT/Top-Private',
    course_duration_years: 4,
    loan_amount: 1200000,
    tenure_months: 84,
    purpose: 'B.Tech Mechanical Engineering at NIT Trichy. Strong GATE score (99.2 percentile). Targeting PSU placements (ONGC, BHEL) with confirmed salary of ₹12-15 LPA. Strong alumni network support.',
    trust_score: {
      score: 76,
      tier: 'Low Risk',
      components: {
        institutionTier: 82,
        courseEmployability: 74,
        coApplicantStrength: 65,
        documentVerification: 95,
        incomeStability: 58,
      },
    },
    current_lowest_rate: 10.00,
    bid_count: 3,
    auction_ends_at: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'open',
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    co_applicant: { name: 'Suresh Mehta', relation: 'Father', annual_income: 850000 },
  },
  {
    id: 'lr-006',
    student_id: 's-006',
    student_name: 'Priya Sharma',
    degree: 'B.Pharm + M.Pharm',
    institution: 'JSS College of Pharmacy',
    institution_tier: 'NIT/Top-Private',
    course_duration_years: 5,
    loan_amount: 1400000,
    tenure_months: 96,
    purpose: 'Integrated B.Pharm + M.Pharm program. Scholarship recipient. Strong research internship at Sun Pharma. Targeting R&D roles with leading pharmaceutical MNCs.',
    trust_score: {
      score: 68,
      tier: 'Moderate Risk',
      components: {
        institutionTier: 65,
        courseEmployability: 72,
        coApplicantStrength: 55,
        documentVerification: 90,
        incomeStability: 48,
      },
    },
    current_lowest_rate: 11.50,
    bid_count: 2,
    auction_ends_at: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'open',
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockBids: Bid[] = [
  {
    id: 'bid-001',
    loan_request_id: 'lr-001',
    lender_id: 'l-001',
    lender_name: 'HDFC Bank',
    interest_rate: 9.25,
    tenure_months: 84,
    processing_fee_percent: 0.5,
    special_conditions: 'No prepayment penalty after 12 EMIs',
    status: 'active',
    created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bid-002',
    loan_request_id: 'lr-002',
    lender_id: 'l-002',
    lender_name: 'State Bank of India',
    interest_rate: 7.10,
    tenure_months: 120,
    processing_fee_percent: 0,
    special_conditions: 'Vidyalakshmi scheme applicable. Moratorium until 6 months post-course completion.',
    status: 'active',
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bid-003',
    loan_request_id: 'lr-003',
    lender_id: 'l-003',
    lender_name: 'Axis Bank',
    interest_rate: 7.75,
    tenure_months: 60,
    processing_fee_percent: 0.75,
    special_conditions: 'Dedicated relationship manager. Pre-approved credit card during course.',
    status: 'active',
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
];

export const mockLenders: Lender[] = [
  {
    id: 'l-001',
    name: 'HDFC Bank',
    type: 'Private Bank',
    rating: 'AAA',
    total_disbursed_crore: 12400,
    active_bids: 18,
    created_at: new Date().toISOString(),
  },
  {
    id: 'l-002',
    name: 'State Bank of India',
    type: 'PSU Bank',
    rating: 'AAA',
    total_disbursed_crore: 28000,
    active_bids: 31,
    created_at: new Date().toISOString(),
  },
  {
    id: 'l-003',
    name: 'Axis Bank',
    type: 'Private Bank',
    rating: 'AA+',
    total_disbursed_crore: 8900,
    active_bids: 12,
    created_at: new Date().toISOString(),
  },
  {
    id: 'l-004',
    name: 'Avanse Financial',
    type: 'NBFC',
    rating: 'AA',
    total_disbursed_crore: 4200,
    active_bids: 9,
    created_at: new Date().toISOString(),
  },
];

export const mockAdminStats: AdminStats = {
  total_loan_requests: 1284,
  total_disbursed_crore: 847,
  active_auctions: 312,
  avg_interest_rate: 8.4,
  avg_savings_percent: 22,
  total_students: 4891,
  total_lenders: 24,
  total_bids: 18432,
};
